### ISSUE TITLE
Implement sorting for all columns

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#5]
Currently, the sorting does not seem to work.

**Comment by Kogoro** [comment]
Solved with the new Single Export HTML in 88a06ef

**Comment by tthuem** [comment]
Still does not work for citations. Comparison appear to be string based.

**Comment by tthuem** [comment]
Again, does not work for citations. Seems to be string comparison again.

**Comment by tthuem** [comment]
If this works, we can release the first version.

**Comment by Kogoro** [comment]
Tested it again with Chrome, Firefox and Vivaldi. All browsers in the latest version and all sortings worked well including citations. In the tests, Firefox is only slower than the other two.

**Comment by tthuem** [comment]
![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/16234675/61ab6b86-37d2-11e6-9ff4-12cf22bc6fe5.png)

Still does not work for me.

**Comment by Kogoro** [comment]
Okay now I know the error. Through the brackets and the overall count the cells aren't numbers. So the solution should be to remove the complete numbers in the filter algorithm. It does not happen on my side because I did not have yearly citation count enabled.

**Comment by tthuem** [comment]
Oh, then it was my fault. I'm fine with removing the total number in brackets.

**Comment by Kogoro** [comment]
Can you test it again? In my test, it works with cells like "8 (16)".

**Comment by tthuem** [comment]
Still does not work...

**Comment by tthuem** [comment]
Please test with more than one digit for some entries. For one digit, everything works fine.

**Comment by Kogoro** [comment]
I have found out that I was working on the wrong function and that the return value for the sorting of numbers was wrong (must be -1 or 1). Also, the indices were wrong for the new layout. So now it should work on all columns.

**Comment by tthuem** [comment]
Sortings seems to be slower now, but it works. :)
